{
 "title": "Performance Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Latency - 0.99",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{grpc_type=\"unary\"}[5m])) by (grpc_service,le))",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Latency - 0.90",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_server_handling_seconds_bucket{grpc_type=\"unary\"}[5m])) by (grpc_service,le))",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Latency - 0.50",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{grpc_type=\"unary\"}[5m])) by (grpc_service,le))",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Latency - 0.25",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(grpc_server_handling_seconds_bucket{grpc_type=\"unary\"}[5m])) by (grpc_service,le))",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(container_cpu_load_average_10s{container_label_io_kubernetes_pod_namespace=\"authority-edgenet-slice-cachecash\", container_label_io_kubernetes_pod_name!~\"cachecash.*|grafana.*|prometheus.*|jaeger.*|filebeat.*|kibana.*|elastic.*\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_io_kubernetes_pod_namespace=\"authority-edgenet-slice-cachecash\", container_label_io_kubernetes_pod_name!~\"cachecash.*|grafana.*|prometheus.*|jaeger.*|filebeat.*|kibana.*|elastic.*\"})"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_io_kubernetes_pod_namespace=\"authority-edgenet-slice-cachecash\", container_label_io_kubernetes_pod_name!~\"cachecash.*|grafana.*|prometheus.*|jaeger.*|filebeat.*|kibana.*|elastic.*\"}[5m]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "-sum(rate(container_network_receive_bytes_total{container_label_io_kubernetes_pod_namespace=\"authority-edgenet-slice-cachecash\", container_label_io_kubernetes_pod_name!~\"cachecash.*|grafana.*|prometheus.*|jaeger.*|filebeat.*|kibana.*|elastic.*\"}[5m]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_io_kubernetes_pod_namespace=\"authority-edgenet-slice-cachecash\", container_label_io_kubernetes_pod_name=~\"cache-.*\"}[5m]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "- sum(rate(container_network_receive_bytes_total{container_label_io_kubernetes_pod_namespace=\"authority-edgenet-slice-cachecash\", container_label_io_kubernetes_pod_name=~\"cache-.*\"}[5m]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{container_label_io_kubernetes_pod_namespace=\"authority-edgenet-slice-cachecash\", container_label_io_kubernetes_pod_name!~\"cachecash.*|grafana.*|prometheus.*|jaeger.*|filebeat.*|kibana.*|elastic.*\"}",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_io_kubernetes_pod_namespace=\"authority-edgenet-slice-cachecash\", container_label_io_kubernetes_pod_name!~\"cachecash.*|grafana.*|prometheus.*|jaeger.*|filebeat.*|kibana.*|elastic.*\"}",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_io_kubernetes_pod_namespace=\"authority-edgenet-slice-cachecash\", container_label_io_kubernetes_pod_name!~\"cachecash.*|grafana.*|prometheus.*|jaeger.*|filebeat.*|kibana.*|elastic.*\"}[5m])",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{container_label_io_kubernetes_pod_namespace=\"authority-edgenet-slice-cachecash\", container_label_io_kubernetes_pod_name!~\"cachecash.*|grafana.*|prometheus.*|jaeger.*|filebeat.*|kibana.*|elastic.*\"}[5m])",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "I/O Utilization Write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{container_label_io_kubernetes_pod_namespace=\"authority-edgenet-slice-cachecash\", container_label_io_kubernetes_pod_name!~\"cachecash.*|grafana.*|prometheus.*|jaeger.*|filebeat.*|kibana.*|elastic.*\"}[5m])",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "I/O Utilization Read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{container_label_io_kubernetes_pod_namespace=\"authority-edgenet-slice-cachecash\", container_label_io_kubernetes_pod_name!~\"cachecash.*|grafana.*|prometheus.*|jaeger.*|filebeat.*|kibana.*|elastic.*\"}[5m])",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  }
 ]
}