{
 "title": "Go Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Goroutines",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_goroutines{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Go threads",
   "type": "gauge",
   "description": "Number of OS threads created.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_threads{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Frees",
   "type": "gauge",
   "description": "Total number of frees.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_frees_total{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Allocated Bytes (in use)",
   "type": "gauge",
   "description": "Number of bytes allocated and still in use.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Used Bytes Bucket Hash Table",
   "type": "gauge",
   "description": "Number of bytes used by the profiling bucket hash table.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_buck_hash_sys_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Allocated Bytes (total per 1h)",
   "type": "gauge",
   "description": "Total number of bytes allocated, even if freed.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[1h])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Used Bytes",
   "type": "gauge",
   "description": "Number of bytes used for garbage collection system metadata.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_gc_sys_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC CPU Fraction",
   "type": "gauge",
   "description": "The fraction of this program's available CPU time used by the GC since the program started.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Heap Bytes (idle)",
   "type": "gauge",
   "description": "Number of heap bytes waiting to be used.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_idle_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Allocated Heap Bytes (in use)",
   "type": "gauge",
   "description": "Number of heap bytes allocated and still in use.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Allocated Heap Objects",
   "type": "gauge",
   "description": "Number of allocated objects.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_objects{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Heap Bytes (in use)",
   "type": "gauge",
   "description": "Number of heap bytes that are in use.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Obtained Heap Bytes",
   "type": "gauge",
   "description": "Number of heap bytes obtained from system.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Released Heap Bytes",
   "type": "gauge",
   "description": "Number of heap bytes released to OS.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_released_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Total Pointer Lookups",
   "type": "gauge",
   "description": "Total number of pointer lookups.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_lookups_total{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Last Run",
   "type": "gauge",
   "description": "Number of seconds since 1970 of last garbage collection.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_last_gc_time_seconds{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Bytes (in use by mcache)",
   "type": "gauge",
   "description": "Number of bytes in use by mcache structures.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_mcache_inuse_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Total Mallocs",
   "type": "gauge",
   "description": "Total number of mallocs.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Bytes (used by mcache)",
   "type": "gauge",
   "description": "Number of bytes used for mcache structures obtained from system.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_mcache_sys_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Bytes (used by mspan)",
   "type": "gauge",
   "description": "Number of bytes used for mspan structures obtained from system.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_mspan_sys_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Bytes (in use by mspan)",
   "type": "gauge",
   "description": "Number of bytes in use by mspan structures.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Next - Heap Bytes",
   "type": "gauge",
   "description": "Number of heap bytes when next garbage collection will take place.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_next_gc_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Bytes Used For Other Allocations",
   "type": "gauge",
   "description": "Number of bytes used for other system allocations.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_other_sys_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Bytes (in use by stack)",
   "type": "gauge",
   "description": "Number of bytes in use by the stack allocator.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Obtained Bytes (for stack)",
   "type": "gauge",
   "description": "Number of bytes obtained from system for stack allocator.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_stack_sys_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Obtained Bytes",
   "type": "gauge",
   "description": "Number of bytes obtained from system.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Invocation Durations (Q=0)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Invocation Durations (Q=0.25)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.25\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Invocation Durations (Q=0.5)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.5\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Invocation Durations (Q=0.75)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.75\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Invocation Durations (Q=1)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"1\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Invocation Durations Summary",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds_sum{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Invocation Durations Count",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 144 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds_count{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}