{
 "title": "GRPC Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Completed RPCs (aborted)",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"Aborted\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Completed RPCs (already exists)",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"AlreadyExists\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Completed RPCs (canceled)",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"Canceled\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Completed RPCs (data loss)",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"DataLoss\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Completed RPCs (deadline exceeded)",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"DeadlineExceeded\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Completed RPCs (failed precondition)",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"FailedPrecondition\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Completed RPCs (internal)",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"Internal\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Completed RPCs (invalid argument)",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"InvalidArgument\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Completed RPCs (not found)",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"NotFound\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Completed RPCs (OK)",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"OK\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Completed RPCs (out of range)",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"OutOfRange\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Completed RPCs (permission denied)",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"PermissionDenied\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Completed RPCs (resource exhausted)",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"ResourceExhausted\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Completed RPCs (unauthenticated)",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"Unauthenticated\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Completed RPCs (unavailable)",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"Unavailable\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Completed RPCs (unimplemented)",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"Unimplemented\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Completed RPCs (unknown)",
   "type": "graph",
   "description": "Total number of RPCs completed on the server, regardless of success or failure.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_code=\"Unknown\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "RPC Stream Messages (received)",
   "type": "graph",
   "description": "Total number of RPC stream messages received on the server.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_msg_received_total{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "RPC Stream Messages (sent)",
   "type": "graph",
   "description": "Total number of gRPC stream messages sent by the server.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_msg_sent_total{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Total RPCs Started",
   "type": "graph",
   "description": "Total number of RPCs started on the server.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_started_total{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}