{
 "title": "Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total CPU Time Spent",
   "type": "graph",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}"
    }
   ]
  },
  {
   "title": "Max Open File",
   "type": "gauge",
   "description": "Maximum number of open file descriptors.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_max_fds{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}"
    }
   ]
  },
  {
   "title": "Open File",
   "type": "gauge",
   "description": "Number of open file descriptors.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_open_fds{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "gauge",
   "description": "Resident memory size in bytes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}"
    }
   ]
  },
  {
   "title": "Process Start Time",
   "type": "gauge",
   "description": "Start time of the process since unix epoch in seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "gauge",
   "description": "Virtual memory size in bytes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}"
    }
   ]
  },
  {
   "title": "Max Available Virtual Memory",
   "type": "gauge",
   "description": "Maximum amount of virtual memory available in bytes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_max_bytes{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}"
    }
   ]
  },
  {
   "title": "Served Scrapes",
   "type": "gauge",
   "description": "Current number of scrapes being served.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_in_flight{app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}"
    }
   ]
  },
  {
   "title": "Total Served Scrapes (200)",
   "type": "gauge",
   "description": "Total number of scrapes by HTTP status code.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{code=\"200\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}"
    }
   ]
  },
  {
   "title": "Total Served Scrapes (500)",
   "type": "gauge",
   "description": "Total number of scrapes by HTTP status code.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{code=\"500\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}"
    }
   ]
  },
  {
   "title": "Total Served Scrapes (503)",
   "type": "gauge",
   "description": "Total number of scrapes by HTTP status code.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{code=\"503\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}"
    }
   ]
  },
  {
   "title": "Total Served Scrapes (503)",
   "type": "gauge",
   "description": "Total number of scrapes by HTTP status code.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{code=\"503\",app!~\"grafana|prometheus|jaeger|metrics\",job=\"kubernetes-pods\"}"
    }
   ]
  }
 ]
}